{
  "hash": "dfd912784f97e63aed53e12866cbc519",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Liz Crouse\"\ndate: 2/13/26\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\necho = FALSE\n\n# Load required packages\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(stringr)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tigris)\nlibrary(sf)\nlibrary(viridis)\nlibrary(RColorBrewer)\nlibrary(knitr)\nlibrary(scales)\n\n\n# Load spatial data\npa_hospitals <- st_read(\"C:/Users/lizmc/Desktop/Y2S2/ppa/crouse/labs/lab_2/data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `C:\\Users\\lizmc\\Desktop\\Y2S2\\ppa\\crouse\\labs\\lab_2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\npa_counties <- st_read(\"C:/Users/lizmc/Desktop/Y2S2/ppa/crouse/labs/lab_2/data/Pennsylvania_County_Boundaries\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `C:\\Users\\lizmc\\Desktop\\Y2S2\\ppa\\crouse\\labs\\lab_2\\data\\Pennsylvania_County_Boundaries' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts <- tracts(\"PA\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |=========                                                             |  14%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |=====================                                                 |  31%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |========================================================              |  81%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |===============================================================       |  91%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================|  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nplot(pa_hospitals)\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(pa_counties)\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(pa_tracts)\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n\n```{.r .cell-code}\nst_crs(pa_hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset? **223**\n- How many census tracts? **3,446**\n- What coordinate reference system is each dataset in? **Hospitals and counties are in WGS 84; tracts are in NAD83.**\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nvariables <- c(mhi = \"B19013_001\",\n               pop = \"B01003_001\",\n               m65_66 = \"B01001_020\",\n    m67_69 = \"B01001_021\",\n    m70_74 = \"B01001_022\",\n    m75_79 = \"B01001_023\",\n    m80_84 = \"B01001_024\",\n    m85p   = \"B01001_025\",\n\n    f65_66 = \"B01001_044\",\n    f67_69 = \"B01001_045\",\n    f70_74 = \"B01001_046\",\n    f75_79 = \"B01001_047\",\n    f80_84 = \"B01001_048\",\n    f85p   = \"B01001_049\"\n  )\n\n\ntract_demographics <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = variables,\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n  \n)\ntract_demographics <- tract_demographics %>%\n  mutate(\n    pop_65plus =\n      (m65_66E + m67_69E + m70_74E + m75_79E + m80_84E + m85pE +\n      f65_66E + f67_69E + f70_74E + f75_79E + f80_84E + f85pE),\n\n    pct_65plus = (pop_65plus / popE) * 100\n  )\n\n\n# Join to tract boundaries\ntract_demographics <- left_join(tract_demographics, pa_tracts, by = \"GEOID\")\n\n#Initial calculations\nsum(is.na(tract_demographics$mhiE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 63\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(tract_demographics$mhiE, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77527.23\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using? **5-Year ACS 2022**\n- How many tracts have missing income data? **63**\n- What is the median income across all PA census tracts? **$77,527.23***\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold) \n2. Significant elderly population (choose an appropriate threshold) \n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nvulnerable_tracts <- tract_demographics %>%\n  filter(mhiE < 64300 & pct_65plus > 25)\nold_tracts <- tract_demographics %>%\n  filter(pct_65plus > 25)\nlowinc_tracts <- tract_demographics %>%\n  filter(mhiE < 64300)\n```\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why? I chose $64,300 as my low-income threshold because it is 200% of the PA poverty line for a household of four. 200% poverty line is often used as a metric for eligibility for social services, which would likely coincide with the tracts that need additional health services. This represents about 40% of tracts.\n- What elderly population threshold did you choose and why? I chose 25% because that means at least one in four individuals in the tract are 65+, meaning extra health services may be needed.\n- How many tracts meet your vulnerability criteria? **230**\n- What percentage of PA census tracts are considered vulnerable by your definition? 6.7%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nst_geometry(vulnerable_tracts) <- \"geometry\"\nvulnerable_tracts <- vulnerable_tracts %>%\n  st_transform(crs = 2272)\npa_hospitals <- pa_hospitals %>%\n  st_transform(crs = 2272)\n# Calculate distance from each tract centroid to nearest hospital\ntract_centroids <- st_centroid(vulnerable_tracts)\nvulnerable_tracts <- vulnerable_tracts %>%\n  mutate(\n    nearest_hosp = st_distance(\n      tract_centroids, pa_hospitals$geometry[st_nearest_feature(tract_centroids, pa_hospitals)],\n      by_element = TRUE))\n\nvulnerable_tracts <- vulnerable_tracts %>%\n  mutate(\n    nearest_hosp_miles = as.numeric(nearest_hosp) / 1609.34)\n\nmean(vulnerable_tracts$nearest_hosp_miles, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.62521\n```\n\n\n:::\n\n```{.r .cell-code}\ntracts_15p <- vulnerable_tracts %>%\n  filter(nearest_hosp_miles > 15)\n```\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection **I used EPSG 2272 because it is a project coordinate system specific to the southern part of Pennsylvania, meaning it will provide more accurate measurements.\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts? **18.64 mi**\n- What is the maximum distance? **95.66 mi**\n- How many vulnerable tracts are more than 15 miles from the nearest hospital? **90**\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_tracts <- vulnerable_tracts %>%\n  mutate(service_level = case_when(nearest_hosp_miles > 15 ~ \"underserved\",\n            TRUE ~ \"served\"))\nvulnerable_tracts %>%\n  count(service_level)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 2 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1204213 ymin: 144992.2 xmax: 2806953 ymax: 1044690\nProjected CRS: NAD83 / Pennsylvania South (ftUS)\n# A tibble: 2 × 3\n  service_level     n                                                   geometry\n* <chr>         <int>                            <MULTIPOLYGON [US_survey_foot]>\n1 served          139 (((1364680 306535, 1364760 306588.4, 1364926 306701.3, 13…\n2 underserved      91 (((1468789 242704.4, 1468958 243992.2, 1469205 246386.1, …\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved? **90**\n- What percentage of vulnerable tracts are underserved? **39%**\n- Does this surprise you? Why or why not? **This does not surprise me. Lower income tracts with high elderly populations are often more rural and therefore may have less access to services. If anything, I am surprised it is not a larger proportion.**\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties <- st_transform(pa_counties, st_crs(vulnerable_tracts))\ncounty_statistics <- st_join(vulnerable_tracts, pa_counties[\"COUNTY_NAM\"])\n\n# Aggregate statistics by county\n\ncounty_statistics_summary <- county_statistics %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    n_vuln_tracts = n(),\n    n_unders_tracts = sum(service_level == \"underserved\", na.rm = TRUE),\n    underserved_pct = (n_unders_tracts / n_vuln_tracts) * 100,\n    avg_dist_nearest_hosp = mean(nearest_hosp_miles, na.rm = TRUE),\n    total_pop_vuln = sum(popE, na.rm = TRUE))\n\nunderserved_counties <- county_statistics_summary %>%\n  filter(underserved_pct == 100)\n\n\ncountygeo_stat_summary <- pa_counties %>%\n  st_join(county_statistics_summary)\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts? **By my parameters for under-service, there are 17 counties in PA that are entirely underserved. The five with the least service (furthest average distance to nearest hospital) are Dauphin, Perry, Sullivan, Bradford, and Pike Counties.**\n- Which counties have the most vulnerable people living far from hospitals? **Counties that are 100% underserved with populations greater than 10,000 are Wayne, McKean, Pike, Tioga, and Clarion Counties.**\n- Are there any patterns in where underserved counties are located? **The largest concentration of the most severely underserved tracts is in north central PA, a rural area distant from PA's two major population centers of Pittsburgh and Philadelphia.**\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n\n\nunderserved_counties_nogeom <- underserved_counties %>%\n  st_drop_geometry() %>%\n  arrange(desc(avg_dist_nearest_hosp)) %>%\n  slice(1:10)\n  \nunderserved_table <- underserved_counties_nogeom %>%\n   mutate(\n    n_vuln_tracts = comma(n_vuln_tracts),\n    n_unders_tracts = comma(n_unders_tracts),\n    total_pop_vuln = comma(total_pop_vuln),\n    underserved_pct = percent(underserved_pct / 100, accuracy = 0.1),\n    avg_dist_nearest_hosp = round(avg_dist_nearest_hosp, 1)) %>%\n  kable(col.names = c(\"County\",\"# Vulnerable Tracts\",\"# Underserved Tracts\",\"% Tracts Underserved\",\"Average Distance from Tract to Nearest Hospital\", \"Total Vulnerable Population\"), caption = \"Counties with high populations of elderly and low income individuals with inequitable access to hospitals\")\n```\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\nggplot(countygeo_stat_summary) + \n  geom_sf(aes(fill = underserved_pct), color = \"black\") +\n  scale_fill_viridis_b(\n    option = \"mako\",\n    direction = -1,\n    name = \n      \"% Underserved\") +\n  theme_void() + \n  labs(title = \"Percentage of Underserved Tracts by County\")\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\npa_tracts <- pa_tracts %>%\n  st_transform(2272)\n\ntracts_service_level <- pa_tracts %>%\n  st_join(vulnerable_tracts[\"service_level\"], join = st_within)\ntracts_service_level <- tracts_service_level %>%\n  mutate(service_level = ifelse(is.na(service_level), \"served\", service_level))\ntracts_service_level %>% \n  count(service_level)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 2 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1189586 ymin: 140905.3 xmax: 2814854 ymax: 1165942\nProjected CRS: NAD83 / Pennsylvania South (ftUS)\n  service_level    n                       geometry\n1        served 3355 MULTIPOLYGON (((1318298 149...\n2   underserved   91 MULTIPOLYGON (((1468789 242...\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot() + \n  geom_sf(\n    data = tracts_service_level,\n    aes(fill = service_level),\n    color = NA) +\n  geom_sf(\n    data = pa_counties,\n    fill = NA,\n    color = \"black\",\n    size = 0.2) +\n  scale_fill_manual(\n    values = c(\n      \"underserved\" = \"red\",\n      \"served\" = NA),\n    na.value = NA) +\n  theme_void() +\n  labs(\n    title = \"Vulnerable & Underserved Tracts in PA Counties\", subtitle = \"Tracts with low median incomes, high 65+ population, and >15 miles to nearest hospital\",\n    fill = \"Service Level\")\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(data = vulnerable_tracts, aes(x = nearest_hosp_miles)) + \n  geom_histogram(binwidth = 5, color = \"black\") +\n    scale_x_continuous(\n    limits = c(0, NA),\n    expand = c(0, 0)\n  ) +\n  scale_y_continuous(\n    limits = c(0, NA),\n    expand = c(0, 0)) +\n     labs(title = \"Distribution of distances to nearest hospital among vulnerable PA census tracts\",\n     x = \"Distance to nearest hospital (mi)\",\n     y = \"Number of tracts\",\n     caption = \"The nearest hospital for over 90 vulnerable tracts is more than 15 miles away.\")\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n\nphl <- counties(state = \"PA\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |=========                                                             |  14%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |=====================                                                 |  31%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |=======================                                               |  34%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |==============================                                        |  44%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |========================================                              |  58%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |==========================================                            |  61%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |============================================                          |  64%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |===================================================                   |  74%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |========================================================              |  81%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |==========================================================            |  84%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |===============================================================       |  91%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |=================================================================     |  94%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================|  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\nphl <- phl %>%\n  filter(NAMELSAD == \"Philadelphia County\")\nphl <- phl %>% st_transform(2272)\n\ncrime_phl <- st_read(\"C:/Users/lizmc/Desktop/Y2S2/ppa/crouse/labs/lab_2/data/incidents_part1_part2(1)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `incidents_part1_part2' from data source \n  `C:\\Users\\lizmc\\Desktop\\Y2S2\\ppa\\crouse\\labs\\lab_2\\data\\incidents_part1_part2(1)' \n  using driver `ESRI Shapefile'\nreplacing null geometries with empty geometries\nSimple feature collection with 152556 features and 13 fields (with 3718 geometries empty)\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.27421 ymin: 5.684342e-14 xmax: 5.684342e-14 ymax: 40.13718\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncrime_phl <- crime_phl %>% st_transform(2272)\ncrime_phl <- st_filter(crime_phl, phl)\n                     \nschools_phl <- st_read(\"C:/Users/lizmc/Desktop/Y2S2/ppa/crouse/labs/lab_2/data/Schools\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Schools' from data source \n  `C:\\Users\\lizmc\\Desktop\\Y2S2\\ppa\\crouse\\labs\\lab_2\\data\\Schools' \n  using driver `ESRI Shapefile'\nSimple feature collection with 490 features and 14 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8378628 ymin: 4852555 xmax: -8345686 ymax: 4884813\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nschools_phl <- schools_phl %>% st_transform(2272)\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\nI chose to look at crimes in school zones to identify which schools might be at the highest safety risk, especially during commutes.\n- What is the data source and date? \nBike network: Department of Streets via OpenDataPhilly, last updated October 2025\nSchools: Department of Planning and Development via OpenDataPhilly, last updated January 2026\n- How many features does it contain?\nSchools: 490\nCrime:148,812\n- What CRS is it in? Did you need to transform it? \nBoth were in WGS 84, transformed to PA South 2272\n\n---\n\n2. **Pose a research question**\nWhich school zones are surrounded by the most (reported) crime?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Clean dataset by eliminating duplicates\n\nschools_phl <- schools_phl %>%\n  filter(!is.na(school_nam), school_nam != \"\")\nschools_unique <- schools_phl %>%\n  group_by(school_nam) %>%\n  summarise(\n    geometry = st_union(geometry),\n    .groups = \"drop\")\n\n#Create buffers\nschool_buffers <- st_buffer(schools_unique, dist = 1000)\n\n#Join with crime data\ncrime_in_school_zones <- st_join(\n  crime_phl,\n  school_buffers,\n  join = st_within,\n  left = FALSE)\n\n#Count number of crimes in buffer zones (point in polygon)\ncrime_by_school <- crime_in_school_zones %>%\n  group_by(school_nam) %>%  \n  summarise(\n    n_crimes = n(),\n    .groups = \"drop\")\n\n#Spatial join back to buffers\nschool_buffers_crime <- school_buffers %>%\n  left_join(\n    st_drop_geometry(crime_by_school),\n    by = \"school_nam\") %>%\n  mutate(\n    n_crimes = replace_na(n_crimes, 0))\n\n#Plot density of crimes in school buffer zones\nggplot() +\n  geom_sf(data = school_buffers_crime,\n          aes(fill = n_crimes),\n          color = \"NA\",\n          alpha = 0.7) +\n    geom_sf(data = phl,\n    fill = NA,\n    color = \"black\",\n    linewidth = 0.8) +\n  scale_fill_viridis_c(name = \"# Crimes in 1000ft\") +\n  theme_void() +\n  labs(title = \"School Safety Zones (1000 ft) and Crime Incidents\")\n```\n\n::: {.cell-output-display}\n![](lab2_crouse_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Identify school zones with the highest number of crimes for potential interventions\nhighest_risk_schools <- school_buffers_crime %>%\n  st_drop_geometry() %>%\n  slice_max(n_crimes, n= 10)\n\nhighest_risk_table <- highest_risk_schools %>%\n  kable(col.names = c(\"School Name\", \"# of reported crimes in 1000 ft radius (2025)\"), caption = \"Schools with the most reported crimes within 1000 foot radius, 2025\")\n```\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nAn analysis of reported crimes in 2025 within 1,000 feet of schools shows clear clustering of high-crime school zones on the eastern side of the city. First, a cluster appears in the Kensington area, showing the highest number of crimes. Then, another cluster appears in North/Northeast Philadelphia. However, of the top ten schools with the most crime in 1,000 feet, about half are in the Center City area. This reveals an obstacle in the data: areas with more density experience more crime because there is more activity. While this can still provide telling information about school safety, it is important to consider the context of population density and how it may contribute to designations of schools as \"safe\" or \"unsafe.\"\n\n",
    "supporting": [
      "lab2_crouse_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}